name: coup_boardgame
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_spinkit: ^5.2.0
  responsive_framework: ^1.1.1
  flutter_datetime_picker: ^1.5.1
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  get_storage: ^2.1.1
  flutter_easyloading: ^3.0.5
  json_annotation: ^4.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true