// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY84nvrbzfFZee1VtCeQp-PR1rFRNM-5k',
    appId: '1:89031302087:web:03175f82642eae035c57e2',
    messagingSenderId: '89031302087',
    projectId: 'coup-boardgame',
    authDomain: 'coup-boardgame.firebaseapp.com',
    storageBucket: 'coup-boardgame.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW6bAAsNNT1Wz_Fdanrnj_6b-4YXEKXpg',
    appId: '1:89031302087:android:8f931c7ed2992a045c57e2',
    messagingSenderId: '89031302087',
    projectId: 'coup-boardgame',
    storageBucket: 'coup-boardgame.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbJEWBTgfgv8yKmVxJSlQBOEBH_y43rqQ',
    appId: '1:89031302087:ios:58a340694bf2a5655c57e2',
    messagingSenderId: '89031302087',
    projectId: 'coup-boardgame',
    storageBucket: 'coup-boardgame.appspot.com',
    iosBundleId: 'com.example.coupBoardgame',
  );
}
